### ISSUE TITLE
Bug on code

### ISSUE THREAD

**Issue by Blackkong1998** [aalanwar/Data-Driven-Predictive-Control#1]
Hi Aalanwar,

Thank you very much for the open source code!
I got a question when I run ZPC.m, on line  211, you created **card_cen**, which is a Linear matrix variable 6x1 (full, real, 1 variable)
Coefficient range: 1 to 5.5. 
On the line 213,  **card_zono = zonotope([card_cen,[R{i}.generators;zeros(1,genleni)]]);**
the bug is: Error inputArgsCheck (On line 111)
----------------------------------
Wrong value for the first input argument.
  The right value: numeric (nonnan)
  Type 'help zonotope' for more information.
Error ZPC (On line 213)
        card_zono = zonotope([card_cen,[R{i}.generators;zeros(1,genleni)]]);
----------------------------------
On my understanding, this card_cen is a nan numerical value, so it cannot be used to create a zonotope. Could you help me on this issue? Thank you in advance!

**Comment by aalanwar** [comment]
Hi Tianyuan,

Thanks for your interest. I am not able to regenerate the error. 
Are you sure of the following:
1- CORA toolbox is not in the path. 
2-  The whole folder of this repo and subfolders are inside the Matlab path. 
?

**Comment by Blackkong1998** [comment]
Hi Aalanwar,

thank you! I deleted the path of CORA just now, and the bug is solved.
